fix: A global trace dispatcher is duplicated
In line 18, 'tracing_subscriber' is already set. Therefore, Delete the duplicated section.

- Full Error Message -

thread 'main' panicked at src/main.rs:182:14:
initialized subscriber succesfully: SetGlobalDefaultError("a global default trace dispatcher has already been set")